# Generated by Django 2.2 on 2022-11-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('is_staff', models.BooleanField(default=True)),
                ('SCHEDULE', models.CharField(choices=[('AM', '07:00-15:00'), ('PM', '15:00-23:00')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('is_staff', models.BooleanField(default=False)),
                ('SUBSCRIPTION', models.CharField(choices=[('1M', 'One month'), ('3M', 'Six month'), ('6M', 'One year'), ('UL', 'Unlimited')], default='UL', max_length=2)),
                ('SERVICES', models.CharField(choices=[('LW', 'Losing weight'), ('GW', 'Gain weight'), ('BD', 'Bodybuilder'), ('AT', 'Athleticism')], default='LW', max_length=2)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_api.InstructorProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
