# Generated by Django 2.2 on 2022-11-22 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('is_staff', models.BooleanField(default=True)),
                ('schedule', models.CharField(choices=[('AM', '07:00-15:00'), ('PM', '15:00-23:00')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('is_staff', models.BooleanField(default=False)),
                ('subscriptions', models.CharField(choices=[('1M', 'One month'), ('3M', 'Six month'), ('6M', 'One year'), ('UL', 'Unlimited')], max_length=2)),
                ('services', models.CharField(choices=[('LW', 'Losing weight'), ('GW', 'Gain weight'), ('BD', 'Bodybuilder'), ('AT', 'Athleticism')], max_length=2)),
                ('schedule', models.CharField(choices=[('AM', '07:00-15:00'), ('PM', '15:00-23:00')], max_length=2)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_api.InstructorProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_day', models.DateField()),
                ('ending_day', models.DateField()),
                ('goal', models.CharField(max_length=255)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_api.InstructorProfile')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_api.MemberProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=100)),
                ('day', models.DateField()),
                ('repeat', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_api.Plan')),
            ],
        ),
    ]
